### ISSUE TITLE
将所有 Markdown 文件生成到 API 文档站

### ISSUE THREAD

**Issue by TechQuery** [EasyWebApp/WebCell#24]
## 技术参考

- TypeStrong/typedoc#2288
- https://typedoc.org/options/input/#readme

**Comment by wangrunlin** [comment]
是否考虑不使用 `typedoc` 生成其它文档？

**Comment by TechQuery** [comment]
> 是否考虑不使用 `typedoc` 生成其它文档？

主要想套用一套文档站的布局。

我们可以只生成一次 TypeDoc，再自己写 TS 脚本读 `index.html` 来替换正文。

**Comment by TechQuery** [comment]
> > 主要想套用一套文档站的布局。
> > 
> > 我们可以只生成一次 TypeDoc，再自己写 TS 脚本读 `index.html` 来替换正文。
> 
> 感觉 TypeDoc 官方不支持的话，要做很多改造的内容

我这个方案只需要 `zx` 加 `jsdom` 写个几十行的脚本。

**Comment by TechQuery** [comment]
另外，Migration 文档后面翻译的时候，首篇引文我翻译了：https://fcc-cd.dev/article/translation/3-reasons-why-i-stopped-using-react-setstate-ab73fc67a42e/

**Comment by TechQuery** [comment]
> 虽然已经把所有文档都生成了，但还是建议使用 VitePress, Astro 等工具生成文档站，SEO，翻译等效果会更好。
> 
> 左侧导航栏也会更清晰，目前的左侧只是源码生成的类型。建议 typedoc 作为文档站的补充。

但我们目前就是生成的类型信息为主，少量 Markdown 文档为辅。
