### ISSUE TITLE
支持IE11的slot处理和ssr吗

### ISSUE THREAD

**Issue by chenyulun** [EasyWebApp/WebCell#4]
支持slot低版本和ssr处理吗

**Comment by TechQuery** [comment]
1. Web Components 官方 polyfill 对 IE 11 `<slot />` 的支持貌似还有问题：https://stackoverflow.com/questions/66393616/angular11-webcomponents-polyfills-ie11-nojoy
2. SSR 的支持我正在研究**标准提案**：https://web.dev/declarative-shadow-dom/

**Comment by TechQuery** [comment]
新标准 `ElementInternals` 提供了对 `<template shadowRootMode="open" />` 的支持，因此 WebCell v3 基于此提供了对 SSR 的组件引擎级支持：

https://github.com/EasyWebApp/WebCell/blob/619146c9e2edb96d80e7086e5a4362b6c0adb25c/source/WebCell.tsx#L44-L55

但还需要类似 Next.js 这样的开发框架来输出符合新标准的 HTML 代码。

**Comment by TechQuery** [comment]
> SSR 的支持我正在研究标准提案：https://web.dev/declarative-shadow-dom/

新标准已经发布，我也实现了它的 polyfill：https://github.com/EasyWebApp/declarative-shadow-dom-polyfill
